language: node_js
node_js:
   - "4.3"
env:
  global:
    #GH_TOKEN
    - secure: hKQ4isSsa5cHA0obJ0LqRZVcJA3T5oAiBqP8UQ6zhriAefDkxYbGYHfkC5y6G8MTaGupucHzx2SqKdUz/qCK5ndGBsn9cOB6ZAnaEMTiVXDE9EV+1O1k5rO41mWGt+qXTJT5XFabF1NeGQOrWR7kxtNvuNRLD+DUOtanif8a4iSjcDlpCTBlf/msZqRQRPO6j54SlAvSQPrb/uJ2Mc+ZkrlpF3vlzczmFK//EE+SAf9NhuPMvjmAeDYl3b5XFotI89O2QMnExLSnh5sdEX7qtcB8Ryrj895+OBT0KYzeH2DDEkulJgEYtFPyKfdkdnVudNlaG5rJxCJwIzBqeTLJtC/txikTT9R2uOfUygzFRpF4OGqSCUVxR+Q09E2qyQKKawc9xFJGCvzlJgjKSX5xG2/dA9WMvF+AZwbBcBqvG51DjnBE+4XJPhh9bCVp9aVQgYZwAHVSfBocBxqlCzJ5dWi2Hq4BVNSeIsk0FRvLJqt2U/i/3CR470d8ZxQ8/n9uigBrC4l7HfRZqbPGprlr8EJfGbzXYSb3DZ2jT7niKYDvNTGjBXYlie6cV4A3KSQwsv80q7FSTP4t97c+HM5pX9IkeuOL0+Ws674QDz+THlBA4w72x7qvHQT44YMM+LBWjJ2UwX20QDnr+zrNDT7hFgZsXoXVZw71c5nBQi3JaPg=

install:
  - npm install --global browserify
  - npm install
script:
  - npm run mytest
  - npm run size
  - npm run build
