language: node_js
node_js:
  - '6.3'
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install --global browserify
  - npm install
script:
  - npm run mytest
  - npm run size
  - npm run build
  - bash scripts/publish-static-demos.sh
GH_TOKEN:
  - secure: >-
      ofN7TY5jJp+/0+JeVYe18moqgeu19VSR32VAeMcPKsy76wxCN2o0LBi997EGbCYqjdZTG2sZsgtU8NhQ0NI24X1w9Se1nziJ7WSntfUpHOfRAD/OtT0kYupIsZVuvUOVYVWk3Xc5bzAEGBw2JNczSpGEgCph4VSKf9l8Sv0MdC7HVcAx8o6kOvgNlu8yC5SFgieDt9AvsDeVY4/cSnq6iNsh9lPAN5kOZz345hgjcHNqluYKhWN0qOLEdmqZuuBGoNSu6B5KiwyKzD8FBeOolvVirLIoPNka0XbLDEFbMojGC+SpST5YPlEBZNZ6nHzV9pauCrT/xMDvfZCqLFrxEyjP1c5TXeBziKKCNiKVtdfT4AouxP2o/oRb5sRKisnqCyP/4Y8k7RHlfqgww5VjnDRW9vBFOD4sKo9kvXNNkanQ/vzpf9G6wmyREXgSrVhky3Mz0EkxQCFqNoIlpjIe84We0N9iXxMhdOWY29f1Ljo5KnVwDgctEEUMbyQnVMPxH2ApxkwOyBF/3GzBPI9mPxAZoKQwRJ5h6Fb/BueoLADawDkEz4OEzm+eLzJXZFhREAlHJ73GNUq9YuWA10gHrtAiEjTJVX384AJyu/tmiuJx3cTLLZlPfWBRGWYNM6g1T05WKqxkY0LWlkALeaON9ypGwNiU5YFh/N9+FwLOBHo=
