sudo: required
language: node_js
node_js:
  - '6.3'
env:
  global:
    - CXX=g++-4.8
    #GH_TOKEN
    - secure: >-
        a+F0PgKFUW+9tbIX2s3RR/Raeh9/IVbBvgnnK/GdKw+1zJWxcpY18Vuc1/VDwLIT/kya0gP8ioc+ea4jbTPq86+bOVA+Z0iW2sfg9IBqft6Kgvjzye427wrsRR90QCulbAJYgquTXLuLbrwg8Zzp0pQF5wkyIx81hfFbCkti71Y8kM9PE/BvlVK5aGUdhNRUTH3YmeCNNqGfnhwtkQhrg2SaBStioyi+TZBDHyKj76giBEtuFSVUnJpdvI1G3BmUmKYFqUR9OQ41ydP1w712HwQCGunng0P8PiNVY8HTINCcn+F6R8exBNZ9eo9w5pQqzVsrSxdcrZnfLmd1LM+umO/4+Yz85/e1oXC5lavEwhAuI2LeVgvRxryCxgH2j+f7N83cW1iKlxF5AwxwXUp5Ew6soVF1mFO5qo9F4aQm4s+fPo/kiyChJzhTUD9g/6k64TFROZsiD69VJf099F1qX35IR1wIJHXTSTJPNoeeQbpCct0nk3B9Piv+EBvdbqYfRfMf08yahImKSV+n1zhzVljY1J1B/ao831lf07FML4Z1t3RlJMRUGUWV5Wk69EA4zjNB7qDmjKyHPxJwNlo0Sawc1OBGZrMcpNX2Ds34BYSHPbA3fIdGShP+Ckyh1aoklJlHPcP9HkhyiykBVtpBLH7mP8J5c7ljbxcI8znc1uM=

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install --global browserify
  - npm install
script:
  - npm run mytest
  - npm run size
  - npm run build
  - bash scripts/publish-static-demos.sh
